#import AC_mean_amip_data
import AC_mean_amip_plot #import compute_metrics
import AC_mean_amip_table
import AC_mean_amip_taylorD_plot
import AC_mean_amip_line_taylorD_html
import AC_DC_cl_p_plot
import AC_amip_contour_html
import DC_amip_contour_html
import DC_amip_line_harmonicD_plot
import DC_mean_amip_line_harmonicD_html
import Daily_amip_PDF_plot
import Daily_amip_PDF_plot_html 
import write_html
