package:
    name: arm_diags
    version: 1.0

source:
    git_url: git@github.com:ARM-DOE/arm-gcm-diagnostics.git

build:
    number: 0
    script: python setup.py install
    script_env:
     - VERSION
     - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools

  run:
    - cdp
    - cdms2
    - cdutil
    - genutil
    - numpy

about:
    home: https://github.com/ARM-DOE/arm-gcm-diagnostics/
    summary: This is a new version of ARM Diagnostics.

