#===========================================================================================================================
# Code for diagnosing convective onset metrics -- Original from Neelin Group at UCLA
#---------------------------------------------------------------------------------------------------------------------------
# V4 Development
    # ---------------------------------------------------------------------------------------
    # Refactored to use xarray instead of cdms2/cdutil
    # Maintained original functionality while modernizing the code
    # ---------------------------------------------------------------------------------------
#===========================================================================================================================
import numpy as np
import numpy.ma as ma
import glob
import matplotlib.pyplot as plt
import os
import scipy.io
import xarray as xr

# Convective onset metrics generated by the Neelin group, UCLA
# Original code: Kathleen Schiro, python version 22 Dec 2016, references privided in detail from convective_onset_statistics_ARM_Diagnostics.py

from .convection_onset_statistics import convection_onset_statistics

def convection_onset(parameter):
    """
    Calculate convection onset metrics for ARM sites.
    
    Analyzes the relationship between precipitation and column water vapor
    for different ARM sites, generating statistics and plots.
    """
    variables = parameter.variables
    test_path = parameter.test_data_path
    obs_path = parameter.obs_path
    cmip_path = parameter.cmip_path
    output_path = parameter.output_path
    sites = parameter.sites
    
    test_model = parameter.test_data_set 
    arm_name = parameter.arm_filename

    print('============================================================')
    print(f'Create Convection Onset Metrics: {sites[0]}')
    print('============================================================')
    
    # Read in observation data
    precip_threshold = 0.5
    for index, site in enumerate(sites):
        # Set site-specific parameters
        if site == 'twpc1':     # twpc1
            cwv_max = 85
            cwv_min = 28
            bin_width = 1.5
            sitename = 'Manus Island'
        elif site == 'twpc2':     # twpc2
            cwv_max = 70
            cwv_min = 28
            bin_width = 2.0
            sitename = 'Nauru'
        elif site == 'twpc3':     # twpc3
            cwv_max = 85
            cwv_min = 28
            bin_width = 2.0
            sitename = 'Darwin'
        elif site == 'sgpc1':     # sgp
            cwv_max = 75
            cwv_min = 20
            bin_width = 2.0
            sitename = 'SGP'
        elif site == 'nsac1':     # nsa
            cwv_max = 50
            cwv_min = 20
            bin_width = 2.0
            sitename = 'NSA'
        elif site == 'enac1':     # ena
            cwv_max = 75
            cwv_min = 20
            bin_width = 2.0
            sitename = 'ENA'
        elif site == 'maom1':     # mao
            cwv_max = 85
            cwv_min = 20
            bin_width = 2.0
            sitename = 'Manacapuru'
    
        # Generate new folder given site names
        if not os.path.exists(os.path.join(output_path, 'figures', site)):
            os.makedirs(os.path.join(output_path, 'figures', site)) 
        output_path_co = os.path.join(output_path, 'figures', site)

        # Process variables for observation data
        precip = None
        prw = None

        for va in variables:
            # Determine file pattern based on naming convention
            if not arm_name:
                filename = glob.glob(os.path.join(obs_path, f'ARMdiag_{va}_1hr_*_{site}.nc'))
                if filename:
                    filename = filename[0]
                else:
                    print(f"No observation file found for {va} at {site}")
                    continue
            else:
                filename = glob.glob(os.path.join(obs_path, f"{site[:3]}armdiags1hr{site[3:5].upper()}*.nc"))
                if filename:
                    filename = filename[0]
                else:
                    print(f"No observation file found for {va} at {site}")
                    continue
            
            print(f'filename: {filename}')
            
            # Open dataset with xarray
            try:
                # Use decode_times=False to avoid time parsing issues
                ds = xr.open_dataset(filename, decode_times=False)
                
                if va in ds:
                    var = ds[va].values
                    print(f'var_shape: {va} {var.shape}')
                    
                    if va == 'pr':
                        precip = var
                        precip[precip < -900] = np.nan
                    elif va == 'prw':
                        prw = var
                        prw[prw < -900] = np.nan
                
                # Close the dataset
                ds.close()
            except Exception as e:
                print(f"Error reading {va} from {filename}: {e}")
                continue
        
        # Process observation data if both variables are available
        if precip is not None and prw is not None:
            convection_onset_statistics(
                precip_threshold, cwv_max, cwv_min, bin_width, 
                prw, precip, 'ARM', output_path_co, sites, sitename
            )
        else:
            print(f"Missing required variables for {site}")
       
        # Process model results
        print('Start model')
        pr_mod_index = 0
        pr_prw_mod = []
        
        for va in variables:
            # Determine file pattern based on naming convention
            if not arm_name:
                filename = glob.glob(os.path.join(test_path, f'*{va}_cfSites_{test_model}*{site}.nc'))
            else:
                test_model_clean = ''.join(e for e in test_model if e.isalnum()).lower()
                print(f"{va}: {test_model_clean} {test_path}")
                filename = glob.glob(os.path.join(test_path, f"{site[:3]}{test_model_clean}subday{site[3:5].upper()}*.nc"))
            
            print(filename)
            
            if not filename:
                print(f"{va}: No sub daily data for test model were found.")
                continue
            
            try:
                # Open dataset with xarray
                ds = xr.open_dataset(filename[0], decode_times=False)
                
                if va in ds:
                    var = ds[va].values
                    
                    # Convert units if needed
                    if va == 'pr':
                        var = var * 3600.  # 'kg m-2 s-1' to 'mm/hr'
                    
                    pr_prw_mod.append(var)
                    pr_mod_index = 1
                
                # Close the dataset
                ds.close()
            except Exception as e:
                print(f"Error reading {va} from {filename[0]}: {e}")
        
        # Process model data if both variables are available
        if pr_mod_index == 1 and len(pr_prw_mod) >= 2:
            convection_onset_statistics(
                precip_threshold, cwv_max, cwv_min, bin_width, 
                pr_prw_mod[1], pr_prw_mod[0], test_model, output_path_co, sites, sitename
            )
        elif pr_mod_index == 1:
            print(f"Not enough variables for model data processing for {site}")